provider: autogen_ext.models.openai.OpenAIChatCompletionClient
config:
  # model: ep-20250408105510-nt22m
  model: ep-20250407104800-9jtk5
  base_url: https://ark.cn-beijing.volces.com/api
  api_key: 
  temperature: 0
  model_info:
    json_output: False
    function_calling: True
    vision: False
    family: unknown
    structured_output: True
